name: Pet Store Api Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean test 

      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com

          # Required mail server port:
          server_port: 465
          
          # Optional (recommended): mail server username:
          username: kenan.gurbuz1610@gmail.com

          # Optional (recommended) mail server password:
          password: ${{ secrets.EMAIL_PASSWORD }}

          # Required mail subject:
          subject: ${{ job.status }} - API TEST

          # Required recipients' addresses:
          to: kg@daxap.io

          # Required sender full name (address can be skipped):
          from: PET STORE API TEST

          # Optional attachments:
          attachments: attachments.zip,git.diff,**/*.html

